behaviors:
  CrabMonster:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 512
      learning_rate: 3.0e-4
      beta: 7.5e-2
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        network_settings:
          memory:
            memory_size: 1024
            sequence_length: 256
        gamma: 0.99
        strength: 1.0
      curiosity:
        network_settings:
          memory:
            memory_size: 1024
            sequence_length: 256
        strength: 0.2
        gamma: 0.99
    max_steps: 2500000
    time_horizon: 64
    summary_freq: 50000